name: gudang_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  supabase_flutter: ^2.5.0
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0

  # Barcode
  mobile_scanner: ^7.1.2 # Modern scanner
  barcode_widget: ^2.0.4
  
  # Printing
  printing: ^5.11.1
  pdf: ^3.10.8

  # UI
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  
  excel: ^4.0.6
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  universal_html: ^2.2.4

  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/